
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSrightUMINUSINTEGER MINUS PLUS PRINT SEMIprogram : PRINT expr SEMI\n               | error SEMIexpr : expr PLUS expr\n            | expr MINUS expr\n            | MINUS expr %prec UMINUS\n            | INTEGER'
    
_lr_action_items = {'PRINT':([0,],[2,]),'error':([0,],[3,]),'$end':([1,7,8,],[0,-2,-1,]),'MINUS':([2,4,5,6,9,10,11,12,13,],[5,10,5,-6,5,5,-5,-3,-4,]),'INTEGER':([2,5,9,10,],[6,6,6,6,]),'SEMI':([3,4,6,11,12,13,],[7,8,-6,-5,-3,-4,]),'PLUS':([4,6,11,12,13,],[9,-6,-5,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expr':([2,5,9,10,],[4,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PRINT expr SEMI','program',3,'p_program','myparser.py',11),
  ('program -> error SEMI','program',2,'p_program','myparser.py',12),
  ('expr -> expr PLUS expr','expr',3,'p_expr','myparser.py',17),
  ('expr -> expr MINUS expr','expr',3,'p_expr','myparser.py',18),
  ('expr -> MINUS expr','expr',2,'p_expr','myparser.py',19),
  ('expr -> INTEGER','expr',1,'p_expr','myparser.py',20),
]
